version: "3"

services: 
  app:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/

  postgres:
    image: postgres
    command: postgres -c 'max_connections=1000'
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - ./.postgress-data:/var/lib/postgresql/data 
