version: "3"

services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: "${DB_USER}"  
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      DATABASE_HOST: "${DB_HOST}" 
    ports:
      - '5432:5432'
    volumes:
      - ./.postgress-data:/var/lib/postgresql/data 